import React, { useState } from 'react';
import { useBills } from '../context/BillContext';
import { TrendingUp, AlertCircle, Calendar, CheckCircle2, DollarSign, Download, Loader2, ArrowRight } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

const dataSets = {
  'Last 6 Months': [
    { name: 'Jan', amount: 400 },
    { name: 'Feb', amount: 300 },
    { name: 'Mar', amount: 600 },
    { name: 'Apr', amount: 800 },
    { name: 'May', amount: 500 },
    { name: 'Jun', amount: 700 },
  ],
  'Last Year': [
    { name: 'Q1', amount: 1200 },
    { name: 'Q2', amount: 1500 },
    { name: 'Q3', amount: 1100 },
    { name: 'Q4', amount: 1900 },
  ]
};

const StatCard = ({ icon: Icon, label, value, subtext, color, onClick }) => (
  <div 
    onClick={onClick}
    className="glass-card stat-card-hover animate-fade-in" 
    style={{ 
      flex: 1, 
      minWidth: '240px', 
      cursor: 'pointer',
      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      position: 'relative',
      overflow: 'hidden'
    }}
  >
    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px' }}>
      <div style={{ 
        width: '52px', 
        height: '52px', 
        borderRadius: '16px', 
        background: `${color}15`, 
        display: 'flex', 
        alignItems: 'center', 
        justifyContent: 'center',
        color: color,
        border: `1px solid ${color}20`
      }}>
        <Icon size={26} />
      </div>
      <div style={{ color: '#10b981', fontSize: '12px', fontWeight: '800', background: 'rgba(16, 185, 129, 0.1)', padding: '4px 10px', borderRadius: '20px', height: 'fit-content' }}>+12.5%</div>
    </div>
    <p style={{ color: 'var(--text-muted)', fontSize: '13px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '8px' }}>{label}</p>
    <h3 style={{ fontSize: '32px', fontWeight: '900', marginBottom: '8px', letterSpacing: '-1px' }}>{value}</h3>
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
      <p style={{ fontSize: '12px', color: 'var(--text-dim)', fontWeight: '600' }}>{subtext}</p>
      <ArrowRight size={14} style={{ color: 'var(--text-dim)', opacity: 0.5 }} className="arrow-icon" />
    </div>
    
    <style dangerouslySetInnerHTML={{ __html: `
      .stat-card-hover:hover {
        transform: translateY(-8px);
        border-color: ${color}40 !important;
        background: ${color}05 !important;
        box-shadow: 0 20px 40px -15px ${color}20 !important;
      }
      .stat-card-hover:hover .arrow-icon {
        opacity: 1 !important;
        transform: translateX(4px);
        color: ${color} !important;
      }
    `}} />
  </div>
);

const Dashboard = ({ setActiveTab }) => {
  const { bills, setShowCalendarModal } = useBills();
  const [isDownloading, setIsDownloading] = useState(false);
  const [timeRange, setTimeRange] = useState('Last 6 Months');
  
  const unpaidBills = bills.filter(b => b.status === 'unpaid');
  const totalDue = unpaidBills.reduce((acc, b) => acc + b.amount, 0);
  const upcomingCount = unpaidBills.length;

  const handleDownload = () => {
    setIsDownloading(true);
    
    const content = `BILL EASE - INTELLIGENT FINANCIAL REPORT\n` +
      `Date: ${new Date().toLocaleDateString()}\n` +
      `------------------------------------------\n\n` +
      `EXECUTIVE SUMMARY\n` +
      `Total Bills Managed: ${bills.length}\n` +
      `Total Obligations: $${bills.reduce((a, b) => a + b.amount, 0).toFixed(2)}\n` +
      `Outstanding Balance: $${totalDue.toFixed(2)}\n` +
      `Upcoming Due Dates: ${upcomingCount}\n\n` +
      `DETAILED BREAKDOWN\n` + 
      bills.map(b => `[${b.status.toUpperCase()}] ${b.title.padEnd(20)} | $${b.amount.toString().padEnd(10)} | Due: ${b.dueDate}`).join('\n') +
      `\n\n------------------------------------------\n` +
      `This report was generated by Nexus AI.`;

    setTimeout(() => {
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `BillEase_Financial_Report_${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      setIsDownloading(false);
    }, 1200);
  };

  return (
    <div className="dashboard-view animate-fade-in">
      <header style={{ marginBottom: '44px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
        <div>
          <h2 style={{ fontSize: '36px', fontWeight: '900', marginBottom: '8px', letterSpacing: '-1px' }}>
            Financial <span className="text-gradient">Hub</span>
          </h2>
          <p style={{ color: 'var(--text-muted)', fontSize: '15px', fontWeight: '500' }}>Morning, John. You have {upcomingCount} bills requiring attention this week.</p>
        </div>
        <div style={{ display: 'flex', gap: '16px' }}>
          <button 
            onClick={() => setShowCalendarModal(true)}
            className="glass-panel" 
            style={{ 
              padding: '12px 24px', 
              border: '1px solid var(--border)', 
              color: 'var(--text-main)', 
              cursor: 'pointer', 
              display: 'flex', 
              alignItems: 'center', 
              gap: '10px', 
              fontWeight: '700', 
              borderRadius: '14px',
              transition: 'var(--transition)'
            }}
          >
            <Calendar size={18} />
            May 2026
          </button>
          <button 
            onClick={handleDownload}
            disabled={isDownloading}
            style={{ 
              padding: '12px 28px', 
              borderRadius: '14px', 
              border: 'none', 
              background: 'var(--primary)', 
              color: 'white', 
              cursor: 'pointer', 
              fontWeight: '700',
              boxShadow: 'var(--shadow-neon)',
              display: 'flex',
              alignItems: 'center',
              gap: '10px',
              minWidth: '200px',
              justifyContent: 'center',
              opacity: isDownloading ? 0.7 : 1,
              transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)'
            }}
          >
            {isDownloading ? <Loader2 size={18} className="animate-spin" /> : <Download size={18} />}
            {isDownloading ? 'Preparing Report...' : 'Generate Report'}
          </button>
        </div>
      </header>

      <div style={{ display: 'flex', gap: '24px', flexWrap: 'wrap', marginBottom: '40px' }}>
        <StatCard 
          icon={AlertCircle} 
          label="Unpaid Obligations" 
          value={`${upcomingCount}`} 
          subtext="Bills pending immediate action" 
          color="#f43f5e" 
          onClick={() => setActiveTab('bills')}
        />
        <StatCard 
          icon={DollarSign} 
          label="Projected Liability" 
          value={`$${totalDue.toFixed(2)}`} 
          subtext="Total amount due this cycle" 
          color="#a855f7" 
          onClick={() => setActiveTab('nexus')}
        />
        <StatCard 
          icon={TrendingUp} 
          label="Spending Index" 
          value="$2,450" 
          subtext="Calculated monthly average" 
          color="#06b6d4" 
          onClick={() => setActiveTab('analytics')}
        />
        <StatCard 
          icon={CheckCircle2} 
          label="Trust Score" 
          value="98.2" 
          subtext="Historical on-time payment rate" 
          color="#10b981" 
          onClick={() => setActiveTab('analytics')}
        />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1.6fr 1fr', gap: '32px' }}>
        <div className="glass-card" style={{ height: '420px', padding: '32px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '32px' }}>
            <h4 style={{ fontSize: '20px', fontWeight: '800' }}>Financial Velocity</h4>
            <select 
              value={timeRange}
              onChange={(e) => setTimeRange(e.target.value)}
              style={{ background: 'var(--bg-deep)', border: '1px solid var(--border)', color: 'var(--text-muted)', borderRadius: '10px', padding: '8px 16px', outline: 'none', cursor: 'pointer', fontWeight: '600', fontSize: '13px' }}
            >
              <option>Last 6 Months</option>
              <option>Last Year</option>
            </select>
          </div>
          <div style={{ width: '100%', height: '280px' }}>
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={dataSets[timeRange]}>
                <defs>
                  <linearGradient id="colorVelocity" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="var(--primary)" stopOpacity={0.4}/>
                    <stop offset="95%" stopColor="var(--primary)" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)" vertical={false} />
                <XAxis dataKey="name" stroke="var(--text-dim)" axisLine={false} tickLine={false} tick={{fontSize: 12, fontWeight: 600}} />
                <YAxis stroke="var(--text-dim)" axisLine={false} tickLine={false} tick={{fontSize: 12, fontWeight: 600}} />
                <Tooltip 
                  contentStyle={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: '14px', boxShadow: '0 10px 30px rgba(0,0,0,0.3)' }}
                  itemStyle={{ color: 'var(--primary)', fontWeight: 700 }}
                />
                <Area type="monotone" dataKey="amount" stroke="var(--primary)" fillOpacity={1} fill="url(#colorVelocity)" strokeWidth={4} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="glass-card" style={{ padding: '32px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '28px' }}>
            <h4 style={{ fontSize: '20px', fontWeight: '800' }}>Priority Dues</h4>
            <div style={{ padding: '4px 12px', background: 'rgba(244, 63, 94, 0.1)', color: '#f43f5e', borderRadius: '20px', fontSize: '11px', fontWeight: '800' }}>URGENT</div>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {unpaidBills.slice(0, 4).map(bill => (
              <div key={bill.id} className="priority-bill-item" style={{ display: 'flex', alignItems: 'center', gap: '16px', padding: '16px', borderRadius: '16px', background: 'rgba(255,255,255,0.02)', border: '1px solid transparent', transition: 'var(--transition)' }}>
                <div style={{ width: '44px', height: '44px', borderRadius: '12px', background: 'rgba(168, 85, 247, 0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--primary)' }}>
                  <TrendingUp size={20} />
                </div>
                <div style={{ flex: 1 }}>
                  <p style={{ fontSize: '14px', fontWeight: '700' }}>{bill.title}</p>
                  <p style={{ fontSize: '11px', color: 'var(--text-dim)', fontWeight: '600' }}>Due in 3 days</p>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <p style={{ fontWeight: '800', fontSize: '15px' }}>${bill.amount}</p>
                  <ArrowRight size={14} style={{ color: 'var(--text-dim)', marginTop: '4px' }} />
                </div>
              </div>
            ))}
            {unpaidBills.length === 0 && <p style={{ color: 'var(--text-dim)', textAlign: 'center', padding: '40px' }}>All accounts are settled!</p>}
          </div>
          <button 
            onClick={() => setActiveTab('bills')}
            style={{ 
              width: '100%', 
              marginTop: '24px', 
              padding: '14px', 
              borderRadius: '14px', 
              border: '1px solid var(--border)', 
              background: 'rgba(255,255,255,0.02)',
              color: 'var(--text-main)',
              fontWeight: '700',
              cursor: 'pointer',
              transition: 'var(--transition)',
              fontSize: '14px'
            }}
            onMouseOver={(e) => { e.currentTarget.style.borderColor = 'var(--primary)'; e.currentTarget.style.background = 'rgba(168, 85, 247, 0.05)'; }}
            onMouseOut={(e) => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.background = 'rgba(255,255,255,0.02)'; }}
          >
            Review Detailed Ledger
          </button>
        </div>
      </div>

      <style dangerouslySetInnerHTML={{ __html: `
        .priority-bill-item:hover {
          background: rgba(255,255,255,0.05) !important;
          border-color: var(--border) !important;
          transform: translateX(4px);
        }
      `}} />
    </div>
  );
};

export default Dashboard;
